// server/src/models/Invoice.ts
// ─────────────────────────────────────────────────────────────
// INVOICE MODEL — Gashuna Hotel Management System
//
// Represents a billing invoice issued to a guest.
// An invoice can contain multiple line items:
//   - Room charges (from the booking)
//   - Restaurant / food orders
//   - Service charges (laundry, tours, transfers)
//   - Any other miscellaneous charges
//
// VAT is calculated at 15% as required by ERCA
// (Ethiopian Revenue and Customs Authority)
//
// Invoice status lifecycle:
//   draft     → being prepared, not yet sent to guest
//   issued    → sent to guest, awaiting payment
//   paid      → fully paid
//   overdue   → payment due date has passed
//   cancelled → invoice was voided
//
// Invoice numbers follow the format: INV-2025-00001
// Generated by generateInvoiceNumber.ts utility
// ─────────────────────────────────────────────────────────────

import { Schema, model, Document, Model, Types } from 'mongoose';

// ── Type Definitions ──────────────────────────────────────────
export type InvoiceStatus =
  | 'draft'
  | 'issued'
  | 'paid'
  | 'overdue'
  | 'cancelled';

export type InvoicePaymentMethod =
  | 'cash'
  | 'telebirr'
  | 'cbe_birr'
  | 'chapa'
  | 'card'
  | 'bank_transfer';

export type InvoiceItemCategory =
  | 'room'
  | 'food'
  | 'service'
  | 'other';

// ── Invoice Line Item Interface ───────────────────────────────
// Each invoice can have multiple line items
export interface IInvoiceItem {
  category: InvoiceItemCategory;
  description: string;
  quantity: number;
  unitPrice: number;
  total: number;
}

// ── Invoice Document Interface ────────────────────────────────
export interface IInvoice extends Document {
  invoiceNumber: string;
  booking?: Types.ObjectId;
  guest: Types.ObjectId;
  items: IInvoiceItem[];
  subtotal: number;
  vatRate: number;
  vatAmount: number;
  total: number;
  amountPaid: number;
  status: InvoiceStatus;
  paymentMethod?: InvoicePaymentMethod;
  chapaTransactionRef?: string;
  issuedAt: Date;
  dueDate?: Date;
  paidAt?: Date;
  issuedBy?: Types.ObjectId;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

// ── Invoice Item Sub-Schema ───────────────────────────────────
// _id: false means line items don't get their own MongoDB _id
// since they only exist as part of the parent invoice
const invoiceItemSchema = new Schema<IInvoiceItem>(
  {
    category: {
      type: String,
      enum: ['room', 'food', 'service', 'other'],
      required: [true, 'Item category is required'],
    },

    description: {
      type: String,
      required: [true, 'Item description is required'],
      trim: true,
    },

    quantity: {
      type: Number,
      required: true,
      default: 1,
      min: [1, 'Quantity must be at least 1'],
    },

    unitPrice: {
      type: Number,
      required: [true, 'Unit price is required'],
      min: [0, 'Unit price cannot be negative'],
    },

    // quantity × unitPrice — calculated before saving
    total: {
      type: Number,
      required: true,
      min: 0,
    },
  },
  { _id: false }
);

// ── Invoice Schema ─────────────────────────────────────────────
const invoiceSchema = new Schema<IInvoice>(
  {
    invoiceNumber: {
      type: String,
      required: [true, 'Invoice number is required'],
      unique: true,
    },

    // An invoice is usually linked to a booking
    // but can also be created standalone (e.g. restaurant-only bill)
    booking: {
      type: Schema.Types.ObjectId,
      ref: 'Booking',
    },

    guest: {
      type: Schema.Types.ObjectId,
      ref: 'Guest',
      required: [true, 'Guest is required for an invoice'],
    },

    items: {
      type: [invoiceItemSchema],
      required: true,
      validate: {
        validator: (items: IInvoiceItem[]) => items.length > 0,
        message: 'Invoice must have at least one line item',
      },
    },

    subtotal: {
      type: Number,
      required: true,
      min: 0,
    },

    // Ethiopian VAT rate — 15% (0.15) as required by ERCA
    vatRate: {
      type: Number,
      default: 0.15,
    },

    vatAmount: {
      type: Number,
      required: true,
      min: 0,
    },

    total: {
      type: Number,
      required: true,
      min: 0,
    },

    amountPaid: {
      type: Number,
      default: 0,
      min: 0,
    },

    status: {
      type: String,
      enum: {
        values: ['draft', 'issued', 'paid', 'overdue', 'cancelled'],
        message: '{VALUE} is not a valid invoice status',
      },
      default: 'draft',
    },

    paymentMethod: {
      type: String,
      enum: [
        'cash',
        'telebirr',
        'cbe_birr',
        'chapa',
        'card',
        'bank_transfer',
      ],
    },

    chapaTransactionRef: {
      type: String,
      trim: true,
    },

    issuedAt: {
      type: Date,
      default: Date.now,
    },

    dueDate: {
      type: Date,
    },

    paidAt: {
      type: Date,
    },

    // Which staff member created/issued this invoice
    issuedBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
    },

    notes: {
      type: String,
      trim: true,
    },
  },
  {
    timestamps: true,
  }
);

// ── Indexes ────────────────────────────────────────────────────
invoiceSchema.index({ invoiceNumber: 1 });
invoiceSchema.index({ guest: 1 });
invoiceSchema.index({ status: 1 });
invoiceSchema.index({ booking: 1 });

// ── Pre-Save Hook: Calculate Totals ───────────────────────────
// Automatically recalculates subtotal, VAT, and total
// every time the invoice items change
invoiceSchema.pre('save', function (next) {
  // Calculate the total for each line item
  this.items.forEach((item) => {
    item.total = Math.round(item.quantity * item.unitPrice * 100) / 100;
  });

  // Sum all line item totals to get the subtotal
  this.subtotal =
    Math.round(
      this.items.reduce((sum, item) => sum + item.total, 0) * 100
    ) / 100;

  // Calculate VAT based on the current vatRate (15% default)
  this.vatAmount = Math.round(this.subtotal * this.vatRate * 100) / 100;

  // Total = subtotal + VAT
  this.total = Math.round((this.subtotal + this.vatAmount) * 100) / 100;

  next();
});

// ── Virtual: Balance Due ──────────────────────────────────────
invoiceSchema.virtual('balanceDue').get(function (this: IInvoice) {
  return Math.max(0, this.total - this.amountPaid);
});

// ── Virtual: Is Fully Paid ────────────────────────────────────
invoiceSchema.virtual('isFullyPaid').get(function (this: IInvoice) {
  return this.amountPaid >= this.total;
});

invoiceSchema.set('toJSON', { virtuals: true });
invoiceSchema.set('toObject', { virtuals: true });

// ── Create and Export Model ───────────────────────────────────
const Invoice: Model<IInvoice> = model<IInvoice>(
  'Invoice',
  invoiceSchema
);

export default Invoice;
